### ISSUE TITLE
Wiki for data products

### ISSUE THREAD

**Issue by drinkingkazu** [DeepLearnPhysics/larcv#10]
Need wiki for data products

**Comment by coreyjadams** [comment]
I can help with this, I think. If you point me towards where you want it and how you want it set up, I can fill in lots of details about the data products.

**Comment by drinkingkazu** [comment]
@coreyjadams I made a skelton documentation (sections & bullet points) here: https://github.com/DeepLearnPhysics/larcv2/wiki/Data-Product

My idea is to introduce from the top-level to the basics: more basic functionalities are described at deeper part of the documentation (this wiki page). Your help would be super appreciated. I will try to fill some of course!

**Comment by drinkingkazu** [comment]
merged into #19
