### ISSUE TITLE
Particle.h destroys information

### ISSUE THREAD

**Issue by coreyjadams** [DeepLearnPhysics/larcv#21]
I don't know what to say here:

`    inline void nu_current_type (short curr) { curr = -1; _current_type = curr; }
`
`    inline void nu_interaction_type (short itype) { itype = -1; _interaction_type = itype; }
`
These functions destroy the information passed to them.  Is there a reason?

**Comment by drinkingkazu** [comment]
c120656a41a93fc144a85413a26f3cae5481e427
