### ISSUE TITLE
Public data sets

### ISSUE THREAD

**Issue by drinkingkazu** [DeepLearnPhysics/larcv#3]
Should have a public data set that can be used in demos (and semi-realistic algorithm development). Start with image classification and semantic segementation data for 2D and 3D.

**Comment by coreyjadams** [comment]
I also have the VOC dataset in larcv format, which we should also make available.  Online storage location TBD.

**Comment by drinkingkazu** [comment]
public data set is becoming available here!
http://deeplearnphysics/DataChallenge

I close this issue for now. We should start opening an individual data request issues from here on! (like get me data X).
