### ISSUE TITLE
Error in simple example following larcv_threadio tutorial

### ISSUE THREAD

**Issue by twongjirad** [DeepLearnPhysics/larcv#7]
I wrote the following script:

https://github.com/DeepLearnPhysics/larcvdataset/blob/master/test_simple.py

It seg-faults. Output not very illuminating. Gist here: https://gist.github.com/twongjirad/7ebccdd02e56ea2564f358b2cb48f2fb

Any thoughts?

I am using ROOT 6.08/02

**Comment by twongjirad** [comment]
Hmm. I think it had to do with the PDG list not being complete. Sorry. Fixed.

**Comment by twongjirad** [comment]
Might consider adding a check for this error to aid user in debugging.

**Comment by drinkingkazu** [comment]
Agreed. Opened https://github.com/DeepLearnPhysics/larcv2/issues/8
